name: Lint Helm Files
on:
    pull_request:
        branches: [main]
jobs:
    lint-helm:
        runs-on: ubuntu-latest
        container: quay.io/helmpack/chart-testing:latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3
            - name: Test Charts
              run: |
                ct install --chart-dirs $(pwd)/templates --charts .
